# Generated by Django 5.2.8 on 2025-12-03 19:12

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID для использования во внешних системах', unique=True, verbose_name='Внешний идентификатор')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма в указанной валюте (минимум 0.01)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма выплаты')),
                ('currency', models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('KZT', 'Казахстанский тенге'), ('BYN', 'Белорусский рубль')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('recipient_details', models.JSONField(help_text='JSON с реквизитами: тип (card/account/wallet), номер, ФИО и др.', verbose_name='Реквизиты получателя')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'В обработке'), ('completed', 'Выполнена'), ('failed', 'Ошибка'), ('cancelled', 'Отменена')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('description', models.TextField(blank=True, default='', help_text='Опциональный комментарий к заявке', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Заявка на выплату',
                'verbose_name_plural': 'Заявки на выплату',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payments_pa_status_b7a5e7_idx'), models.Index(fields=['currency'], name='payments_pa_currenc_0af73b_idx')],
            },
        ),
    ]
