from decimal import Decimal

MAX_PAYOUT_AMOUNT = Decimal('1000000.00')
MIN_PAYOUT_AMOUNT = Decimal('0.01')

RECIPIENT_TYPES = ['card', 'account', 'wallet']
MIN_CARD_NUMBER_LENGTH = 13
MIN_ACCOUNT_LENGTH = 10
MIN_WALLET_ID_LENGTH = 5

CELERY_MAX_RETRIES = 3
CELERY_DEFAULT_RETRY_DELAY = 5
CELERY_TASK_TIME_LIMIT = 60

RATE_LIMIT_PER_MINUTE = 100

DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 1000
